import numpy as np
a=np.array([1,2,3,4,5,6,7,])
print(a)
sum=np.sum(a)
print(sum)
avg=np.mean(a)
print(avg)
mini=np.min(a)
print(mini)
maxi=np.max(a)
stdv=np.std(a)
print(stdv)
imin=np.min(a)
print(imin)
imax=np.max(a)
vari=np.var(a)
print(vari)